"""User model — student and admin roles only.

UUID primary keys are generated by PostgreSQL (``gen_random_uuid()``).
Application code still sets the PK when inserting via SQLAlchemy so that it
can reference the new row immediately; the server_default is a safety net for
direct SQL inserts.

Timestamps use ``server_default=db.text("now()")`` so the DB clock is
authoritative, and ``onupdate`` keeps ``updated_at`` fresh without a Python
lambda, which can be skipped when a row is updated outside SQLAlchemy.
"""
from __future__ import annotations

import enum

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

from ..extensions import db


class UserRole(str, enum.Enum):
    student = "student"
    admin   = "admin"


class User(db.Model):
    __tablename__ = "users"
    __table_args__ = (
        # Partial index: fast lookup of active students for leaderboard queries.
        db.Index("ix_users_role_active", "role", "is_active"),
    )

    id            = db.Column(
                        UUID(as_uuid=False),
                        primary_key=True,
                        server_default=db.text("gen_random_uuid()"),
                    )
    email         = db.Column(db.String(255), unique=True, nullable=False, index=True)
    name          = db.Column(db.String(150), nullable=False)
    password_hash = db.Column(db.Text,        nullable=False)
    role          = db.Column(
                        db.Enum(UserRole, name="userrole"),
                        nullable=False,
                        default=UserRole.student,
                        server_default=UserRole.student.value,
                        index=True,
                    )
    avatar        = db.Column(db.String(8),  nullable=False, server_default="")   # initials / emoji
    is_active     = db.Column(db.Boolean,    nullable=False, server_default=sa.true())
    email_verified = db.Column(db.Boolean,   nullable=False, server_default=sa.false())
    created_at    = db.Column(
                        db.DateTime(timezone=True),
                        nullable=False,
                        server_default=db.text("now()"),
                    )
    updated_at    = db.Column(
                        db.DateTime(timezone=True),
                        nullable=False,
                        server_default=db.text("now()"),
                        onupdate=db.text("now()"),
                    )

    # ── Relationships ──────────────────────────────────────────────────────
    enrollments         = db.relationship("Enrollment",        back_populates="user", lazy="dynamic", cascade="all, delete-orphan")
    lesson_progress     = db.relationship("LessonProgress",    back_populates="user", lazy="dynamic", cascade="all, delete-orphan")
    quiz_attempts       = db.relationship("QuizAttempt",       back_populates="user", lazy="dynamic", cascade="all, delete-orphan")
    points_transactions = db.relationship("PointsTransaction", back_populates="user", lazy="dynamic", cascade="all, delete-orphan")
    user_badges         = db.relationship("UserBadge",         back_populates="user", lazy="dynamic", cascade="all, delete-orphan")
    streak              = db.relationship("UserStreak",        back_populates="user", uselist=False,  cascade="all, delete-orphan")
    purchases           = db.relationship("Purchase",          back_populates="user", lazy="dynamic", cascade="all, delete-orphan")
    pending_orders      = db.relationship("PendingOrder",      back_populates="user", lazy="dynamic", cascade="all, delete-orphan")

    # ── Helpers ────────────────────────────────────────────────────────────
    def is_admin(self) -> bool:
        return self.role == UserRole.admin

    def is_student(self) -> bool:
        return self.role == UserRole.student

    def to_dict(self, include_private: bool = False) -> dict:
        return {
            "id":             self.id,
            "email":          self.email,
            "name":           self.name,
            "role":           self.role.value,
            "avatar":         self.avatar,
            "is_active":      self.is_active,
            "email_verified": self.email_verified,
            "created_at":     self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self) -> str:
        return f"<User {self.email} [{self.role.value}]>"
